export default {
  lastIndex: 18,
  items: [
    {
      id: 1,
      vendorCode: '1',
      name: 'name awd awd awda wdaw dawddawd  fawf awf awfname awd awd awda wdaw dawddawd  fawf awf awfname awd awd awda wdaw dawddawd  fawf awf awf',
      count: 1,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 2,
      vendorCode: '2',
      name: 'name',
      count: 2,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 3,
      vendorCode: '3',
      name: 'name',
      count: 3,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 4,
      vendorCode: '4',
      name: 'name',
      count: 0,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 5,
      vendorCode: '5',
      name: 'name',
      count: 1,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 6,
      vendorCode: '5268548552572',
      name: 'name',
      count: 1,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 7,
      vendorCode: '1',
      name: 'name',
      count: 1,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 8,
      vendorCode: '2',
      name: 'name',
      count: 2,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 9,
      vendorCode: '3',
      name: 'name',
      count: 3,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 10,
      vendorCode: '4',
      name: 'name',
      count: 0,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 11,
      vendorCode: '5',
      name: 'name',
      count: 1,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 12,
      vendorCode: '5268548552572',
      name: 'name',
      count: 1,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 13,
      vendorCode: '1',
      name: 'name',
      count: 1,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 14,
      vendorCode: '2',
      name: 'name',
      count: 2,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 15,
      vendorCode: '3',
      name: 'name',
      count: 3,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 16,
      vendorCode: '4',
      name: 'name',
      count: 0,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 17,
      vendorCode: '5',
      name: 'name',
      count: 1,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
    {
      id: 18,
      vendorCode: '5268548552572',
      name: 'name',
      count: 1,
      price: 100,
      manufacturer: 'USA',
      additionalFields: [],
    },
  ],
  selectedItem: null,
  chunk: [],
};
